apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-laravel-latest
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:87b4705228d66cc60ae37e308662e0d3ec12568a2b1c55e4d299fad655fa7c2f
