apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlflow-exposed-auth-bypass-secret-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/internet-ctf/secrets/mlflow-exposed-auth-bypass-flag/versions/1"
        path: "flag.txt"
