apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-apache
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: /chroot/flag
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: apache-path-traversal-secret-provider
  healthcheck:
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:17135f80aaac1b07a929e1c48240e0ce14c25c29f5aca20dc406e4c5dd59fabd
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:9028a32692498ecb82f003740d42daf2c831ac102410c0d4b720cd4dfff76f42
