apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-gitlab-CVE-2021-22205
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
